#!/bin/sh
echo 'I Pased this line'
whoami
echo 'let see the bee'
ssh -t -t taulantvokshi@examples.buzz <<EOF
 cd ~/jenkins
 pm2 stop all
 git pull
 npm install
 npm run production
 pm2 restart all
 exit
EOF



  